### ISSUE TITLE
Allow use of user IDs/@s in commands and bot responses.

### ISSUE THREAD

**Issue by Xulai** [zmoin/slapBot#2]
Currently the bot will accept any string as input for it's slap subject. 
Instead it should accept a user @ to get a users data then @ that passed in user in the response.
It appears you can get user mentions through a member on the message object passed into the event callback.
 https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=mentions

**Comment by zmoin** [comment]
The bot uses user mentions @ (using regExp) **only**. Closed :)
