### ISSUE TITLE
Add a permission levels list

### ISSUE THREAD

**Issue by Xulai** [zmoin/slapBot#5]
In addition to the existing blacklist and whitelist, add a third list of key pairs so we can denote permission levels.
example being having Zarrin set as admin being able to use special secret new commands, whereas everyone else is considered a default user who can't use special secret new commands.

**Comment by zmoin** [comment]
Working on that. For now, only .stop will be assigned to the admin, for example, and then we can come up with something more?
Thanks to @lastplacer for walking me through the steps!

**Comment by zmoin** [comment]
Added that to the files. Permissions.json can be used to define that and a function in the slapbot.js is used to check for the permissions.
